### PR TITLE
AL-5644 - update to eslint

### PR DESCRIPTION
**Pull request by WORMSS**

### CODE REVIEW

**Comment by WORMSS** [comment]
@OlegRayskiy you might want to check your prettier settings, they seem to be different from normal, .eslint shouldn't have been formatted to be 80 chars instead of 100.

Also, why ignore index.ts, isn't it technically the most important since that is the exposed one?

**Comment by OlegRayskiy** [comment]
> @OlegRayskiy you might want to check your prettier settings, they seem to be different from normal, .eslint shouldn't have been formatted to be 80 chars instead of 100.

Where did you get 80 chars from? It didn't format it to that.

> Also, why ignore index.ts, isn't it technically the most important since that is the exposed one?

because the only thing that it will complain about there is max-len, and since we are disabling that for imports, why not ignore the whole file?

**Comment by WORMSS** [comment]
You are assuming no other issues may arise? If you want to disable max-len for that file, disable max-len, don't need to disable everything.
When prettier is set to 100 chars, it formats the json differently. Unless you are not using prettier for json files at all?

**Comment by OlegRayskiy** [comment]
> When prettier is set to 100 chars, it formats the json differently. Unless you are not using prettier for json files at all?
Are you sure it's not other way around?

**Comment by cmcnicholas** [comment]
conflicts need resolving here (should just require an npm install) azure devops now running pipeline

**Pull request merged**
