### PR TITLE
added zIndex: 0 to all styles to enforce style render ordering

### PR DESCRIPTION
**Pull request by OlegRayskiy**
Don't know what really changed inside openlayers, but this now stops the icons stacking together on top of other styles

### CODE REVIEW

**Comment by WORMSS** [comment]
Have you tried opening file/data explorer when items are on the map?

**Comment by cmcnicholas** [comment]
> Have you tried opening file/data explorer when items are on the map?

Has nothing to do with browser z-index

**Comment by OlegRayskiy** [comment]
If zIndex for styles is undefined then all styles will be rendered in order - fill, stroke, image, text which caused all icons to be always rendered on top.

**Comment by cmcnicholas** [comment]
I think I get this now. Given two features with 3 styles if no z-index is specified the following happens

feature 1 = [style1, style2, style3]
feature 2 = [style1, style2, style3]

1. all style1's processed
2. all style2's processed
3. all style3's processed

whereas specifying z-index 0 my understanding is it will go

1. feature 1 style 1
2. feature 1 style 2
3. feature 1 style 3
4. feature 1 style 1
5. feature 1 style 2
6. feature 1 style 3

this does seem like it would incur a performance hit but seems the right thing to do style wise (not sure why i have never seen it happen in testing though)

**Pull request merged**
